package com.triton.johnson_tap_app.interfaces;

import com.triton.johnson_tap_app.responsepojo.RepairWorkRequestNatureOfWorkResponse;

public interface OnItemClickRepairWorkRequestNatureOfWorkResponseListener {
    void itemClickRepairWorkRequestNatureOfWorkResponseListener(RepairWorkRequestNatureOfWorkResponse.Data repairWorkRequestNatureOfWorkDataResponse);
}
