package com.triton.johnson_tap_app.interfaces;

import com.triton.johnson_tap_app.responsepojo.FailureReportCompDeviceListResponse;

public interface OnItemClickFailureReportFetchDetailsByComIdResponseListener {
    void itemClickFailureReportFetchDetailsByComIdResponseListener(FailureReportCompDeviceListResponse.Data failureReportCompDeviceListDataResponse);
}
